name: EquinoxEquestrian
version: '1.0.1'
main: endcrypt.equinox.EquinoxEquestrian
api-version: '1.20'
depend:
  - ProtocolLib
  - Vault
  - floodgate
softdepend:
  - PlaceholderAPI
  - CMI
  - EssentialsX