name: EquinoxEquestrian
version: '1.0'
main: endcrypt.equinoxEquestrian.EquinoxEquestrian
api-version: '1.20'
depend: [ ProtocolLib, Vault, floodgate ]
softdepend:
  - PlaceholderAPI
commands:
  eq:
    description: Equine Command of EquinoxEquestrian Plugin
    usage: /eq
    aliases: [equine]
  eqadmin:
    description: Admin Command of EquinoxEquestrian Plugin
    aliases: [equineadmin]
  horse:
    description: Horse Command of EquinoxEquestrian Plugin
    usage: /horse
    aliases: [h]
