package endcrypt.equinoxEquestrian.horse.enums;

public enum Breed {

    NONE("None", "None", "None", 13, 15),

    AEGIDIENBERGER("Aegidienberger", "GAITED", "HORSE", 13, 15),
    AKHAL_TEKE("Akhal-Teke", "EXOTIC", "HORSE", 14, 16),
    AMERICAN_INDIAN_HORSE("American Indian Horse", "STOCK", "HORSE", 13, 16.3),
    AMERICAN_MINIATURE_HORSE("American Miniature Horse", "PONY", "PONY", 9, 9),
    AMERICAN_PAINT_HORSE("American Paint Horse", "STOCK", "HORSE", 14, 16.3),
    AMERICAN_QUARTER_HORSE("American Quarter Horse", "STOCK", "HORSE", 14, 16.3),
    AMERICAN_SADDLEBRED("American Saddlebred", "GAITED", "HORSE", 15, 17.3),
    AMERICAN_SHETLAND("American Shetland", "PONY", "PONY", 9, 11.3),
    AMERICAN_SPORT_PONY("American Sport Pony", "PONY", "PONY", 13.2, 14.2),
    AMERICAN_SUGARBUSH_HARLEQUIN_DRAFT("American Sugarbush Harlequin Draft", "DRAFT", "OVERSIZED", 15.2, 17.3),
    AMERICAN_WARMBLOOD("American Warmblood", "WARMBLOOD", "HORSE", 15, 17.3),
    ANDALUSIAN("Andalusian", "BAROQUE", "HORSE", 15, 16.3),
    ANGLO_ARABIAN("Anglo-Arabian", "HOT-BLOODED", "COB", 15.2, 16.3), // Corrected Hot-Blooded
    APPALOOSA("Appaloosa", "STOCK", "HORSE", 14, 16.3),
    APPENDIX_HORSE("Appendix Horse", "STOCK", "HORSE", 15, 17.3),
    ARABIAN("Arabian", "EXOTIC", "COB", 14, 15.3),
    ARALOOSA("Araloosa", "STOCK", "HORSE", 14.2, 17),
    ARDENNES("Ardennes", "DRAFT", "OVERSIZED", 15.2, 18),
    AUSTRALIAN_BRUMBY("Australian Brumby", "WILD", "HORSE", 13, 16.3),
    AUSTRALIAN_RIDING_PONY("Australian Riding Pony", "PONY", "PONY", 11, 14.2),
    AUSTRALIAN_STOCK_HORSE("Australian Stock Horse", "STOCK", "HORSE", 14.2, 17),
    AUSTRALIAN_WARMBLOOD("Australian Warmblood", "WARMBLOOD", "HORSE", 14.2, 17),
    AUSTRIAN_WARMBLOOD("Austrian Warmblood", "WARMBLOOD", "HORSE", 14.2, 17),
    AZTECA("Azteca", "BAROQUE", "HORSE", 14.2, 17),
    BAJAU_PONY("Bajau Pony", "PONY", "PONY", 11, 13.3),
    BARB_HORSE("Barb Horse", "BAROQUE", "HORSE", 14.2, 17),
    BAROCK_PINTO("Barock Pinto", "BAROQUE", "HORSE", 14.2, 17),
    BAVARIAN_WARMBLOOD("Bavarian Warmblood", "WARMBLOOD", "HORSE", 14.2, 17),
    BELGIAN_DRAFT("Belgian Draft", "DRAFT", "OVERSIZED", 15.2, 18),
    BELGIAN_RIDING_PONY("Belgian Riding Pony", "PONY", "PONY", 15.2, 18),
    BELGIAN_SPORT_HORSE("Belgian Sport Horse", "WARMBLOOD", "HORSE", 15.2, 18),
    BELGIAN_WARMBLOOD("Belgian Warmblood", "WARMBLOOD", "HORSE", 15.2, 18),
    BLACK_FOREST_HORSE("Black Forest Horse", "EXOTIC", "HORSE", 13, 16.3),
    BLAZER("Blazer", "STOCK", "HORSE", 13, 16.3),
    BOULONNAIS("Boulonnais", "DRAFT", "OVERSIZED", 14.2, 17),
    BRAZILIAN_SPORT_HORSE("Brazilian Sport Horse", "WARMBLOOD", "HORSE", 15.2, 18),
    BRENTON("Breton", "DRAFT", "OVERSIZED", 14.2, 17),
    BRITISH_RIDING_PONY("British Riding Pony", "PONY", "PONY", 11, 14.2),
    BRITISH_SPOTTED_PONY("British Spotted Pony", "PONY", "PONY", 11, 14.2),
    BRITISH_WARMBLOOD("British Warmblood", "WARMBLOOD", "HORSE", 15.2, 18),
    BUDYONNY("Budyonny", "STOCK", "HORSE", 14.2, 17),
    CALABRESE("Calabrese", "GAITED", "HORSE", 14, 16),
    CAMARGUE("Camargue", "EXOTIC", "HORSE", 13.2, 15),
    CAMPOLINA("Campolina", "GAITED", "HORSE", 14.2, 16),
    CANADIAN_SPORT_HORSE("Canadian Sport Horse", "WARMBLOOD", "HORSE", 15.2, 17),
    CASPIAN_HORSE("Caspian Horse", "EXOTIC", "PONY", 11, 13.2),
    CHEVAL_CANADIAN("Cheval Canadian", "BAROQUE", "HORSE", 14.2, 16),
    CHINCOTEAGUE_PONY("Chincoteague Pony", "WILD", "PONY", 11, 14),
    CLEVELAND_BAY("Cleveland Bay", "WARMBLOOD", "HORSE", 15.2, 16.2),
    CLYDESDALE("Clydesdale", "DRAFT", "OVERSIZED", 16, 18),
    CONNEMARA("Connemara", "PONY", "PONY", 12, 14.2),
    COLORADO_RANGER("Colorado Ranger", "STOCK", "HORSE", 14, 16),
    CRIOLLO("Criollo", "GAITED", "HORSE", 13.2, 15),
    CURLY_HORSE("Curly Horse", "EXOTIC", "HORSE", 14, 16),
    CZECH_WARMBLOOD("Czech Warmblood", "WARMBLOOD", "HORSE", 15.2, 17),
    DALES_PONY("Dales Pony", "PONY", "PONY", 12, 14),
    DANISH_SPORT_PONY("Danish Sport Pony", "PONY", "PONY", 13, 14.2),
    DANISH_WARMBLOOD("Danish Warmblood", "WARMBLOOD", "HORSE", 15.2, 17),
    DARTMOOR_PONY("Dartmoor Pony", "PONY", "PONY", 11, 13),
    DOLE_HORSE("Dole Horse", "DRAFT", "HORSE", 14.2, 16),
    DUTCH_HARNESS_HORSE("Dutch Harness Horse", "WARMBLOOD", "OVERSIZED", 15.2, 17),
    DUTCH_HEAVY_DRAFT("Dutch Heavy Draft", "DRAFT", "OVERSIZED", 16, 18),
    DUTCH_RIDING_PONY("Dutch Riding Pony", "PONY", "PONY", 12.2, 14.2),
    DUTCH_WARMBLOOD("Dutch Warmblood", "WARMBLOOD", "HORSE", 15.2, 17),
    EXMOOR_PONY("Exmoor Pony", "WILD", "PONY", 11, 13),
    ERISKAY_PONY("Eriskay Pony", "PONY", "PONY", 11, 13),
    FALABELLA("Falabella", "EXOTIC", "PONY", 8, 10),
    FAROESE_PONY("Faroese Pony", "PONY", "PONY", 11, 13),
    FELL_PONY("Fell Pony", "PONY", "PONY", 12, 14),
    FINNISH_WARMBLOOD("Finnish Warmblood", "WARMBLOOD", "HORSE", 15.2, 17),
    FLORIDA_CRACKER_HORSE("Florida Cracker Horse", "GAITED", "HORSE", 14, 16),
    FREDRIKSBORGERS("Frederiksborger", "BAROQUE", "HORSE", 15.2, 16.2),
    FRENCH_SADDLE_PONY("French Saddle Pony", "PONY", "PONY", 12, 14),
    FRENCH_TROTTER("French Trotter", "GAITED", "HORSE", 15, 16.2),
    FRIESIAN("Friesian", "BAROQUE", "HORSE", 14.2, 17),
    FRIESIAN_SPORT_HORSE("Friesian Sport Horse", "BAROQUE", "HORSE", 14.2, 16),
    GALICENO("Galiceno", "STOCK", "PONY", 11, 13),
    GEORGIAN_GRANDE("Georgian Grande", "GAITED", "OVERSIZED", 15.2, 17),
    GERMAN_RIDING_PONY("German Riding Pony", "PONY", "PONY", 12, 14.2),
    GERMAN_SPORT_HORSE("German Sport Horse", "WARMBLOOD", "HORSE", 15.2, 17),
    GERMAN_WARMBLOOD("German Warmblood", "WARMBLOOD", "HORSE", 15.2, 17),
    GRONINGEN_HORSE("Groningen Horse", "DRAFT", "OVERSIZED", 15.2, 17),
    GYPSY_VANNER("Gypsy Vanner", "EXOTIC", "COB", 13, 15),
    HACKNEY_HORSE("Hackney Horse", "HOT-BLOODED", "HORSE", 14.2, 16),
    HACKNEY_PONY("Hackney Pony", "HOT-BLOODED", "PONY", 12, 14),
    HAFLINGER("Haflinger", "GRADE", "HORSE", 13.2, 15),
    HANNOVERIAN("Hanoverian", "WARMBLOOD", "HORSE", 15.2, 17),
    HEQU_HORSE("Hequ Horse", "STOCK", "HORSE", 14, 16),
    HIGHLAND_PONY("Highland Pony", "PONY", "PONY", 12, 14),
    HOKKAIDO_HORSE("Hokkaido Horse", "PONY", "PONY", 11, 13),
    HOLSTEINER("Holsteiner", "WARMBLOOD", "HORSE", 15.2, 17),
    HUCUL_HORSE("Hucul Horse", "GAITED", "PONY", 12, 14),
    HUNGARIAN_WARMBLOOD("Hungarian Warmblood", "WARMBLOOD", "HORSE", 15.2, 17),
    ICELANDIC_HORSE("Icelandic Horse", "GAITED", "PONY", 13, 14.2),
    IOMUD_HORSE("Iomud Horse", "GAITED", "HORSE", 14, 16),
    IRISH_DRAUGHT_HORSE("Irish Draught Horse", "DRAFT", "OVERSIZED", 15.2, 17),
    IRISH_SPORT_HORSE("Irish Sport Horse", "WARMBLOOD", "HORSE", 15.2, 17),
    JINZHOU_HORSE("Jinzhou Horse", "STOCK", "HORSE", 14, 16),
    JUTLAND_HORSE("Jutland Horse", "DRAFT", "HORSE", 14.2, 16),
    KABARDA_HORSE("Kabarda Horse", "STOCK", "HORSE", 14, 16),
    KARABAIR_HORSE("Karabair Horse", "STOCK", "HORSE", 14, 16),
    KARABAKH_HORSE("Karabakh Horse", "EXOTIC", "HORSE", 14.2, 16),
    KAZAKH_HORSE("Kazakh Horse", "STOCK", "HORSE", 14, 16),
    KERRY_BOG_PONY("Kerry Bog Pony", "PONY", "PONY", 11, 13),
    KIGER_MUSTANG_HORSE("Kiger Mustang Horse", "WILD", "HORSE", 13, 15),
    KIRDI_PONY("Kirdi Pony", "PONY", "PONY", 11, 13),
    KISBER_FELVER_HORSE("Kisber Felver Horse", "WARMBLOOD", "OVERSIZED", 15.2, 17),
    KISO_HORSE("Kiso Horse", "STOCK", "PONY", 11, 13),
    KLADRUBY_HORSE("Kladruby Horse", "BAROQUE", "HORSE", 15.2, 17),
    KNABSTRUPPER_HORSE("Knabstrupper Horse", "WARMBLOOD", "HORSE", 14.2, 16),
    KUSHUM_HORSE("Kushum Horse", "STOCK", "HORSE", 14, 16),
    KUSTANAI_HORSE("Kustanai Horse", "STOCK", "HORSE", 14, 16),
    LATVIAN_HORSE("Latvian Horse", "WARMBLOOD", "HORSE", 15.2, 17),
    LITHUANIAN_HEAVY_DRAFT("Lithuanian Heavy Draft", "DRAFT", "OVERSIZED", 16, 18),
    LIPIZZANER("Lipizzaner", "BAROQUE", "HORSE", 14.2, 16),
    LOKAI_HORSE("Lokai Horse", "STOCK", "HORSE", 14, 16),
    LOSINO_HORSE("Losino Horse", "WARMBLOOD", "HORSE", 15.2, 17),
    LUSITANO("Lusitano", "BAROQUE", "HORSE", 14.2, 16),
    MALOPOLSKI_HORSE("Malopolski Horse", "WARMBLOOD", "HORSE", 15.2, 17),
    MANGALARGA("Mangalarga", "GAITED", "HORSE", 14, 16),
    MARWARI_HORSE("Marwari Horse", "EXOTIC", "HORSE", 14, 16),
    M_BAYAR_PONY("M'Bayar Pony", "PONY", "PONY", 11, 13),
    MERENS_PONY("Mérens Pony", "PONY", "PONY", 12, 14),
    MESSARA_HORSE("Messara Horse", "GAITED", "HORSE", 14, 16),
    MISAKI_HORSE("Misaki Horse", "EXOTIC", "PONY", 11, 13),
    MISSOURI_FOX_TROTTER("Missouri Fox Trotter", "GAITED", "HORSE", 14.2, 16),
    MIYAKO_PONY("Miyako Pony", "EXOTIC", "PONY", 11, 13),
    MONGOLIAN_HORSE("Mongolian Horse", "GAITED", "PONY", 12, 14),
    MORAB("Morab", "STOCK", "HORSE", 14, 16),
    MORGAN("Morgan", "STOCK", "HORSE", 14.2, 15.2),
    MOYLE_HORSE("Moyle Horse", "EXOTIC", "HORSE", 13, 15),
    MUSTANG("Mustang", "WILD", "HORSE", 13, 15),
    MURGESE_HORSE("Murgese Horse", "BAROQUE", "OVERSIZED", 15.2, 17),
    NATIONAL_SHOW_HORSE("National Show Horse", "WARMBLOOD", "HORSE", 15.2, 17),
    NEW_FOREST_PONY("New Forest Pony", "PONY", "PONY", 12, 14),
    NEW_KIRGIZ_HORSE("New Kirgiz Horse", "STOCK", "HORSE", 14, 16),
    NEWFOUNDLAND_PONY("Newfoundland Pony", "PONY", "PONY", 11, 13),
    NOMA_HORSE("Noma Horse", "PONY", "PONY", 11, 13),
    NOOITGEDACHT_PONY("Nooitgedacht Pony", "PONY", "PONY", 11, 13),
    NORIC_HORSE("Noric Horse", "DRAFT", "OVERSIZED", 15.2, 17),
    NORLAND_HORSE("Nordland Horse", "DRAFT", "HORSE", 14.2, 16),
    NORTHEASTERN_CRIOULO("Northeastern - Crioulo -", "STOCK", "HORSE", 13.2, 15),
    NORTH_SWEDISH_HORSE("North Swedish Horse -", "DRAFT", "HORSE", 15.2, 17),
    NORWEGIAN_FJORD_HORSE("Norwegian Fjord Horse", "EXOTIC", "COB", 13.2, 14.2),
    OB_PONY("Ob Pony", "PONY", "PONY", 11, 13),
    OLDENBURGER("Oldenburger", "WARMBLOOD", "HORSE", 15.2, 17),
    ORLOV_TROTTER("Orlov Trotter", "GAITED", "HORSE", 15, 16.2),
    PANTANEIRO_CRIOULO("Pantaneiro - Crioulo Horse", "STOCK", "HORSE", 13.2, 15),
    PASO_FINO("Paso Fino", "GAITED", "HORSE", 13.2, 15),
    PERCHERON("Percheron", "DRAFT", "OVERSIZED", 16, 18),
    PERUVIAN_PASO("Peruvian Paso", "GAITED", "HORSE", 13.2, 15),
    PINDOS_PONY("Pindos Pony", "PONY", "PONY", 12, 14),
    PINIA_HORSE("Pinia Horse", "STOCK", "PONY", 11, 13),
    PINTABIAN("Pintabian", "STOCK", "HORSE", 14, 16),
    POLISH_KONIK("Polish Konik", "WILD", "HORSE", 12, 14),
    PONY_OF_THE_AMERICAS("Pony of the Americas", "PONY", "PONY", 11.2, 14.2),
    POTTOK("Pottok", "PONY", "PONY", 11, 13),
    PRZEWALSKI("Przewalski", "WILD", "PONY", 12, 14),
    PYRENEAN_TARPAN("Pyrenean Tarpan", "WILD", "PONY", 12, 14),
    QATGANI_HORSE("Qatgani Horse", "EXOTIC", "HORSE", 14, 16),
    QUARAB("Quarab", "STOCK", "HORSE", 14, 16),
    QUARTER_PONY("Quarter Pony", "PONY", "PONY", 11.2, 14.2),
    RACKING_HORSE("Racking Horse", "GAITED", "HORSE", 14.2, 16),
    ROCKY_MOUNTAIN_HORSE("Rocky Mountain Horse", "GAITED", "HORSE", 14, 16),
    RUSSIAN_DON("Russian Don", "GAITED", "HORSE", 14.2, 16),
    RUSSIAN_HEAVY_DRAFT("Russian Heavy Draft", "DRAFT", "OVERSIZED", 16, 18),
    RUSSIAN_TROTTER("Russian Trotter", "GAITED", "HORSE", 15, 16.2),
    SANHE_HORSE("Sanhe Horse", "STOCK", "HORSE", 14, 16),
    SCHLESWIGER_HEAVY_DRAFT("Schleswiger Heavy Draft", "DRAFT", "OVERSIZED", 16, 18),
    SCHWARZWÄLDER_FUCHS("Schwarzwälder Fuchs", "DRAFT", "OVERSIZED", 15.2, 17),
    SELLE_FRANCAIS("Selle Francais", "WARMBLOOD", "HORSE", 15.2, 17),
    SHAGYA_ARABIAN("Shagya Arabian", "HOT-BLOODED", "HORSE", 14.2, 16),
    SHETLAND_PONY("Shetland Pony", "PONY", "PONY", 9, 11.3),
    SHIRE("Shire", "DRAFT", "OVERSIZED", 17, 19),
    SINGLE_FOOTING("Single-Footing", "GAITED", "HORSE", 14, 16),
    SKYROS_PONY("Skyros Pony", "PONY", "PONY", 11, 13),
    SOMALI_PONY("Somali Pony", "PONY", "PONY", 11, 13),
    SORRAIA("Sorraia", "WILD", "HORSE", 13, 15),
    SOVIET_HEAVY_DRAFT("Soviet Heavy Draft", "DRAFT", "OVERSIZED", 16, 18),
    SPANISH_BARB("Spanish Barb", "BAROQUE", "OVERSIZED", 14.2, 16),
    SPANISH_MUSTANG("Spanish Mustang", "WILD", "HORSE", 13, 15),
    SPANISH_NORMAN("Spanish-Norman", "WARMBLOOD", "HORSE", 15.2, 17),
    STANDARDBRED("Standardbred", "GAITED", "HORSE", 15, 16.2),
    SUDAN_COUNTRY_BRED("Sudan Country-Bred", "STOCK", "HORSE", 14, 16),
    SUFFOLK_PUNCH("Suffolk Punch", "DRAFT", "OVERSIZED", 16, 18),
    SWEDISH_WARMBLOOD("Swedish Warmblood", "WARMBLOOD", "HORSE", 15.2, 17),
    TAISHUH_HORSE("Taishuh Horse", "STOCK", "HORSE", 14, 16),
    TARPAN("Tarpan", "WILD", "HORSE", 12, 14),
    TAWLEED_HORSE("Tawleed Horse", "EXOTIC", "HORSE", 14, 16),
    TENNESSEE_WALKING_HORSE("Tennessee Walking Horse", "GAITED", "HORSE", 14.2, 16),
    TERSK_HORSE("Tersk Horse", "GAITED", "HORSE", 14, 16),
    THESSALIAN_HORSE("Thessalian Horse", "STOCK", "HORSE", 14, 16),
    THOROUGHBRED("Thoroughbred", "HOT-BLOODED", "HORSE", 14.2, 17),
    TOKARA_PONY("Tokara Pony", "PONY", "PONY", 11, 13),
    TORI_HORSE("Tori Horse", "WARMBLOOD", "COB", 14.2, 16),
    TRAKHNER("Trakehner", "WARMBLOOD", "HORSE", 15.2, 17),
    UKRAINIAN_SADDLE_HORSE("Ukrainian Saddle Horse", "WARMBLOOD", "HORSE", 15.2, 17),
    VLAAMPERD("Vlaamperd", "BAROQUE", "HORSE", 14.2, 16),
    VLADIMIR_HEAVY_DRAFT("Vladimir Heavy Draft", "DRAFT", "HORSE", 15.2, 17),
    VYATKA_HORSE("Vyatka Horse", "PONY", "PONY", 11, 13),
    WELARA_HORSE("Welara Horse", "PONY", "PONY", 11, 13),
    WELSH_PONY("Welsh Pony", "PONY", "PONY", 11, 14.2),
    WELSH_COB("Welsh Cob", "PONY", "COB", 13, 15),
    WEST_AFRICAN_BARB("West African Barb", "HOT-BLOODED", "COB", 14, 16),
    WESTERN_SUDAN_PONY("Western Sudan Pony", "PONY", "PONY", 11, 13),
    WESTPHALIAN("Westphalian", "WARMBLOOD", "HORSE", 15.2, 17),
    WIELKOPOLSKI_HORSE("Wielkopolski Horse", "WARMBLOOD", "HORSE", 15.2, 17),
    XILINGOL_HORSE("Xilingol Horse", "WARMBLOOD", "COB", 14, 16),
    YAKUT_HORSE("Yakut Horse", "EXOTIC", "PONY", 13, 15),
    YANQI_HORSE("Yanqi Horse", "STOCK", "COB", 13, 15),
    YILI_HORSE("Yili Horse", "STOCK", "COB", 13, 15),
    YONAGUNI_HORSE("Yonaguni Horse", "PONY", "PONY", 11, 13),
    ZANISKARI_PONY("Zaniskari Pony", "EXOTIC", "PONY", 11, 13),
    ZHEMAICHU_HORSE("Zhemaichu Horse", "PONY", "PONY", 11, 13);


    private final String name;
    private final String type;
    private final String size;
    private final double minimumHands;
    private final double maximumHands;

    // Constructor
    Breed(String name, String type, String size, double minimumHands, double maximumHands) {
        this.name = name;
        this.type = type;
        this.size = size;
        this.minimumHands = minimumHands;
        this.maximumHands = maximumHands;
    }

    public String getName() {
        return name;
    }

    public String getType() {
        return type;
    }

    public String getSize() {
        return size;
    }

    public double getMinimumHands() {
        return minimumHands;
    }

    public double getMaximumHands() {
        return maximumHands;
    }

    @Override
    public String toString() {
        return name + " (" + type + ", " + size + ")";
    }
}
