package endcrypt.equinoxEquestrian.horse.enums;

public enum Breed {

    AEGIDIENBERGER("Aegidienberger", "GAITED", "HORSE", 13, 16.3),
    AKHAL_TEKE("Akhal-Teke", "EXOTIC", "HORSE", 14.2, 17),
    AMERICAN_INDIAN_HORSE("American Indian Horse", "STOCK", "HORSE", 13, 16.3),
    AMERICAN_MINIATURE_HORSE("American Miniature Horse", "PONY", "PONY", 9, 9),
    AMERICAN_PAINT_HORSE("American Paint Horse", "STOCK", "HORSE", 14.2, 17),
    AMERICAN_QUARTER_HORSE("American Quarter Horse", "STOCK", "HORSE", 14.2, 17),
    AMERICAN_SADDLEBRED("American Saddlebred", "GAITED", "HORSE", 14.2, 17),
    AMERICAN_SHETLAND("American Shetland", "PONY", "PONY", 11, 13.3),
    AMERICAN_SPORT_PONY("American Sport Pony", "PONY", "PONY", 13.2, 14.2),
    AMERICAN_SUGARBUSH_HARLEQUIN_DRAFT("American Sugarbush Harlequin Draft", "DRAFT", "OVERSIZED", 15.2, 18),
    AMERICAN_WARMBLOOD("American Warmblood", "WARMBLOOD", "HORSE", 14.2, 17),
    ANDALUSIAN("Andalusian", "BAROQUE", "HORSE", 14.2, 17),
    ANGLO_ARABIAN("Anglo-Arabian", "HOT-BLOOD", "HORSE", 14.2, 17),
    APPALOOSA("Appaloosa", "STOCK", "HORSE", 14.2, 17),
    APPENDIX_HORSE("Appendix Horse", "STOCK", "HORSE", 14.2, 17),
    ARABIAN("Arabian", "EXOTIC", "COB", 14.2, 17),
    ARALOOSA("Araloosa", "STOCK", "HORSE", 14.2, 17),
    ARDENNES("Ardennes", "DRAFT", "OVERSIZED", 15.2, 18),
    AUSTRALIAN_BRUMBY("Australian Brumby", "WILD", "HORSE", 13, 16.3),
    AUSTRALIAN_RIDING_PONY("Australian Riding Pony", "PONY", "PONY", 11, 14.2),
    AUSTRALIAN_STOCK_HORSE("Australian Stock Horse", "STOCK", "HORSE", 14.2, 17),
    AUSTRALIAN_WARMBLOOD("Australian Warmblood", "WARMBLOOD", "HORSE", 14.2, 17),
    AUSTRIAN_WARMBLOOD("Austrian Warmblood", "WARMBLOOD", "HORSE", 14.2, 17),
    AZTECA("Azteca", "BAROQUE", "HORSE", 14.2, 17),
    BAJAU_PONY("Bajau Pony", "PONY", "PONY", 11, 13.3),
    BARB_HORSE("Barb Horse", "BAROQUE", "HORSE", 14.2, 17),
    BAROCK_PINTO("Barock Pinto", "BAROQUE", "HORSE", 14.2, 17),
    BAVARIAN_WARMBLOOD("Bavarian Warmblood", "WARMBLOOD", "HORSE", 14.2, 17),
    BELGIAN_DRAFT("Belgian Draft", "DRAFT", "OVERSIZED", 15.2, 18),
    BELGIAN_RIDING_PONY("Belgian Riding Pony", "PONY", "PONY", 15.2, 18),
    BELGIAN_SPORT_HORSE("Belgian Sport Horse", "WARMBLOOD", "HORSE", 15.2, 18),
    BELGIAN_WARMBLOOD("Belgian Warmblood", "WARMBLOOD", "HORSE", 15.2, 18),
    BLACK_FOREST_HORSE("Black Forest Horse", "EXOTIC", "HORSE", 13, 16.3),
    BLAZER("Blazer", "STOCK", "HORSE", 13, 16.3),
    BOULONNAIS("Boulonnais", "DRAFT", "OVERSIZED", 14.2, 17),
    BRAZILIAN_SPORT_HORSE("Brazilian Sport Horse", "WARMBLOOD", "HORSE", 15.2, 18),
    BRENTON("Breton", "DRAFT", "OVERSIZED", 14.2, 17),
    BRITISH_RIDING_PONY("British Riding Pony", "PONY", "PONY", 11, 14.2),
    BRITISH_SPOTTED_PONY("British Spotted Pony", "PONY", "PONY", 11, 14.2),
    BRITISH_WARMBLOOD("British Warmblood", "WARMBLOOD", "HORSE", 15.2, 18),
    BUDYONNY("Budyonny", "STOCK", "HORSE", 14.2, 17),
    CALABRESE("Calabrese", "GAITED", "HORSE"),
    CAMARGUE("Camargue", "EXOTIC", "HORSE"),
    CAMPOLINA("Campolina", "GAITED", "HORSE"),
    CANADIAN_SPORT_HORSE("Canadian Sport Horse", "WARMBLOOD", "HORSE"),
    CASPIAN_HORSE("Caspian Horse", "EXOTIC", "PONY"),
    CHEVAL_CANADIAN("Cheval Canadian", "BAROQUE", "HORSE"),
    CHINCOTEAGUE_PONY("Chincoteague Pony", "WILD", "PONY"),
    CLEVELAND_BAY("Cleveland Bay", "WARMBLOOD", "HORSE"),
    CLYDESDALE("Clydesdale", "DRAFT", "OVERSIZED"),
    CONNEMARA("Connemara", "PONY", "PONY"),
    COLORADO_RANGER("Colorado Ranger", "STOCK", "HORSE"),
    CRIOLLO("Criollo", "GAITED", "HORSE"),
    CURLY_HORSE("Curly Horse", "EXOTIC", "HORSE"),
    CZECH_WARMBLOOD("Czech Warmblood", "WARMBLOOD", "HORSE"),
    DALES_PONY("Dales Pony", "PONY", "PONY"),
    DANISH_SPORT_PONY("Danish Sport Pony", "PONY", "PONY"),
    DANISH_WARMBLOOD("Danish Warmblood", "WARMBLOOD", "HORSE"),
    DARTMOOR_PONY("Dartmoor Pony", "PONY", "PONY"),
    DOLE_HORSE("Dole Horse", "DRAFT", "HORSE"),
    DUTCH_HARNESS_HORSE("Dutch Harness Horse", "WARMBLOOD", "OVERSIZED"),
    DUTCH_HEAVY_DRAFT("Dutch Heavy Draft", "DRAFT", "OVERSIZED"),
    DUTCH_RIDING_PONY("Dutch Riding Pony", "PONY", "PONY"),
    DUTCH_WARMBLOOD("Dutch Warmblood", "WARMBLOOD", "HORSE"),
    EXMOOR_PONY("Exmoor Pony", "WILD", "PONY"),
    ERISKAY_PONY("Eriskay Pony", "PONY", "PONY"),
    FALABELLA("Falabella", "EXOTIC", "PONY"),
    FAROESE_PONY("Faroese Pony", "PONY", "PONY"),
    FELL_PONY("Fell Pony", "PONY", "PONY"),
    FINNISH_WARMBLOOD("Finnish Warmblood", "WARMBLOOD", "HORSE"),
    FLORIDA_CRACKER_HORSE("Florida Cracker Horse", "GAITED", "HORSE"),
    FREDRIKSBORGERS("Frederiksborger", "BAROQUE", "HORSE"),
    FRENCH_SADDLE_PONY("French Saddle Pony", "PONY", "PONY"),
    FRENCH_TROTTER("French Trotter", "GAITED", "HORSE"),
    FRIESIAN("Friesian", "BAROQUE", "HORSE"),
    FRIESIAN_SPORT_HORSE("Friesian Sport Horse", "BAROQUE", "HORSE"),
    GALICENO("Galiceno", "STOCK", "PONY"),
    GEORGIAN_GRANDE("Georgian Grande", "GAITED", "OVERSIZED"),
    GERMAN_RIDING_PONY("German Riding Pony", "PONY", "PONY"),
    GERMAN_SPORT_HORSE("German Sport Horse", "WARMBLOOD", "HORSE"),
    GERMAN_WARMBLOOD("German Warmblood", "WARMBLOOD", "HORSE"),
    GRONINGEN_HORSE("Groningen Horse", "DRAFT", "OVERSIZED"),
    GYPSY_VANNER("Gypsy Vanner", "EXOTIC", "COB"),
    HACKNEY_HORSE("Hackney Horse", "HOT-BLOODED", "HORSE"),
    HACKNEY_PONY("Hackney Pony", "HOT-BLOODED", "PONY"),
    HAFLINGER("Haflinger", "GRADE", "HORSE"),
    HANNOVERIAN("Hanoverian", "WARMBLOOD", "HORSE"),
    HEQU_HORSE("Hequ Horse", "STOCK", "HORSE"),
    HIGHLAND_PONY("Highland Pony", "PONY", "PONY"),
    HOKKAIDO_HORSE("Hokkaido Horse", "PONY", "PONY"),
    HOLSTEINER("Holsteiner", "WARMBLOOD", "HORSE"),
    HUCUL_HORSE("Hucul Horse", "GAITED", "PONY"),
    HUNGARIAN_WARMBLOOD("Hungarian Warmblood", "WARMBLOOD", "HORSE"),
    ICELANDIC_HORSE("Icelandic Horse", "GAITED", "PONY"),
    IOMUD_HORSE("Iomud Horse", "GAITED", "HORSE"),
    IRISH_DRAUGHT_HORSE("Irish Draught Horse", "DRAFT", "OVERSIZED"),
    IRISH_SPORT_HORSE("Irish Sport Horse", "WARMBLOOD", "HORSE"),
    JINZHOU_HORSE("Jinzhou Horse", "STOCK", "HORSE"),
    JUTLAND_HORSE("Jutland Horse", "DRAFT", "HORSE"),
    KABARDA_HORSE("Kabarda Horse", "STOCK", "HORSE"),
    KARABAIR_HORSE("Karabair Horse", "STOCK", "HORSE"),
    KARABAKH_HORSE("Karabakh Horse", "EXOTIC", "HORSE"),
    KAZAKH_HORSE("Kazakh Horse", "STOCK", "HORSE"),
    KERRY_BOG_PONY("Kerry Bog Pony", "PONY", "PONY"),
    KIGER_MUSTANG_HORSE("Kiger Mustang Horse", "WILD", "HORSE"),
    KIRDI_PONY("Kirdi Pony", "PONY", "PONY"),
    KISBER_FELVER_HORSE("Kisber Felver Horse", "WARMBLOOD", "OVERSIZED"),
    KISO_HORSE("Kiso Horse", "STOCK", "PONY"),
    KLADRUBY_HORSE("Kladruby Horse", "BAROQUE", "HORSE"),
    KNABSTRUPPER_HORSE("Knabstrupper Horse", "WARMBLOOD", "HORSE"),
    KUSHUM_HORSE("Kushum Horse", "STOCK", "HORSE"),
    KUSTANAI_HORSE("Kustanai Horse", "STOCK", "HORSE"),
    LATVIAN_HORSE("Latvian Horse", "WARMBLOOD", "HORSE"),
    LITHUANIAN_HEAVY_DRAFT("Lithuanian Heavy Draft", "DRAFT", "OVERSIZED"),
    LIPIZZANER("Lipizzaner", "BAROQUE", "HORSE"),
    LOKAI_HORSE("Lokai Horse", "STOCK", "HORSE"),
    LOSINO_HORSE("Losino Horse", "WARMBLOOD", "HORSE"),
    LUSITANO("Lusitano", "BAROQUE", "HORSE"),
    MALOPOLSKI_HORSE("Malopolski Horse", "WARMBLOOD", "HORSE"),
    MANGALARGA("Mangalarga", "GAITED", "HORSE"),
    MARWARI_HORSE("Marwari Horse", "EXOTIC", "HORSE"),
    M_BAYAR_PONY("M'Bayar Pony", "PONY", "PONY"),
    MERENS_PONY("Mérens Pony", "PONY", "PONY"),
    MESSARA_HORSE("Messara Horse", "GAITED", "HORSE"),
    MISAKI_HORSE("Misaki Horse", "EXOTIC", "PONY"),
    MISSOURI_FOX_TROTTER("Missouri Fox Trotter", "GAITED", "HORSE"),
    MIYAKO_PONY("Miyako Pony", "EXOTIC", "PONY"),
    MONGOLIAN_HORSE("Mongolian Horse", "GAITED", "PONY"),
    MORAB("Morab", "STOCK", "HORSE"),
    MORGAN("Morgan", "STOCK", "HORSE"),
    MOYLE_HORSE("Moyle Horse", "EXOTIC", "HORSE"),
    MUSTANG("Mustang", "WILD", "HORSE"),
    MURGESE_HORSE("Murgese Horse", "BAROQUE", "OVERSIZED"),
    NATIONAL_SHOW_HORSE("National Show Horse", "WARMBLOOD", "HORSE"),
    NEW_FOREST_PONY("New Forest Pony", "PONY", "PONY"),
    NEW_KIRGIZ_HORSE("New Kirgiz Horse", "STOCK", "HORSE"),
    NEWFOUNDLAND_PONY("Newfoundland Pony", "PONY", "PONY"),
    NOMA_HORSE("Noma Horse", "PONY", "PONY"),
    NOOITGEDACHT_PONY("Nooitgedacht Pony", "PONY", "PONY"),
    NORIC_HORSE("Noric Horse", "DRAFT", "OVERSIZED"),
    NORLAND_HORSE("Nordland Horse", "DRAFT", "HORSE"),
    NORTHEASTERN_CRIOULO("Northeastern - Crioulo -", "STOCK", "HORSE"),
    NORTH_SWEDISH_HORSE("North Swedish Horse -", "DRAFT", "HORSE"),
    NORWEGIAN_FJORD_HORSE("Norwegian Fjord Horse", "EXOTIC", "COB"),
    OB_PONY("Ob Pony", "PONY", "PONY"),
    OLDENBURGER("Oldenburger", "WARMBLOOD", "HORSE"),
    ORLOV_TROTTER("Orlov Trotter", "GAITED", "HORSE"),
    PANTANEIRO_CRIOULO("Pantaneiro - Crioulo Horse", "STOCK", "HORSE"),
    PASO_FINO("Paso Fino", "GAITED", "HORSE"),
    PERCHERON("Percheron", "DRAFT", "OVERSIZED"),
    PERUVIAN_PASO("Peruvian Paso", "GAITED", "HORSE"),
    PINDOS_PONY("Pindos Pony", "PONY", "PONY"),
    PINIA_HORSE("Pinia Horse", "STOCK", "PONY"),
    PINTABIAN("Pintabian", "STOCK", "HORSE"),
    POLISH_KONIK("Polish Konik", "WILD", "HORSE"),
    PONY_OF_THE_AMERICAS("Pony of the Americas", "PONY", "PONY"),
    POTTOK("Pottok", "PONY", "PONY"),
    PRZEWALSKI("Przewalski", "WILD", "PONY"),
    PYRENEAN_TARPAN("Pyrenean Tarpan", "WILD", "PONY"),
    QATGANI_HORSE("Qatgani Horse", "EXOTIC", "HORSE"),
    QUARAB("Quarab", "STOCK", "HORSE"),
    QUARTER_PONY("Quarter Pony", "PONY", "PONY"),
    RACKING_HORSE("Racking Horse", "GAITED", "HORSE"),
    ROCKY_MOUNTAIN_HORSE("Rocky Mountain Horse", "GAITED", "HORSE"),
    RUSSIAN_DON("Russian Don", "GAITED", "HORSE"),
    RUSSIAN_HEAVY_DRAFT("Russian Heavy Draft", "DRAFT", "OVERSIZED"),
    RUSSIAN_TROTTER("Russian Trotter", "GAITED", "HORSE"),
    SANHE_HORSE("Sanhe Horse", "STOCK", "HORSE"),
    SCHLESWIGER_HEAVY_DRAFT("Schleswiger Heavy Draft", "DRAFT", "OVERSIZED"),
    SCHWARZWÄLDER_FUCHS("Schwarzwälder Fuchs", "DRAFT", "OVERSIZED"),
    SELLE_FRANCAIS("Selle Francais", "WARMBLOOD", "HORSE"),
    SHAGYA_ARABIAN("Shagya Arabian", "HOT-BLOODED", "HORSE"),
    SHETLAND_PONY("Shetland Pony", "PONY", "PONY"),
    SHIRE("Shire", "DRAFT", "OVERSIZED"),
    SINGLE_FOOTING("Single-Footing", "GAITED", "HORSE"),
    SKYROS_PONY("Skyros Pony", "PONY", "PONY"),
    SOMALI_PONY("Somali Pony", "PONY", "PONY"),
    SORRAIA("Sorraia", "WILD", "HORSE"),
    SOVIET_HEAVY_DRAFT("Soviet Heavy Draft", "DRAFT", "OVERSIZED"),
    SPANISH_BARB("Spanish Barb", "BAROQUE", "OVERSIZED"),
    SPANISH_MUSTANG("Spanish Mustang", "WILD", "HORSE"),
    SPANISH_NORMAN("Spanish-Norman", "WARMBLOOD", "HORSE"),
    STANDARDBRED("Standardbred", "GAITED", "HORSE"),
    SUDAN_COUNTRY_BRED("Sudan Country-Bred", "STOCK", "HORSE"),
    SUFFOLK_PUNCH("Suffolk Punch", "DRAFT", "OVERSIZED"),
    SWEDISH_WARMBLOOD("Swedish Warmblood", "WARMBLOOD", "HORSE"),
    TAISHUH_HORSE("Taishuh Horse", "STOCK", "HORSE"),
    TARPAN("Tarpan", "WILD", "HORSE"),
    TAWLEED_HORSE("Tawleed Horse", "EXOTIC", "HORSE"),
    TENNESSEE_WALKING_HORSE("Tennessee Walking Horse", "GAITED", "HORSE"),
    TERSK_HORSE("Tersk Horse", "GAITED", "HORSE"),
    THESSALIAN_HORSE("Thessalian Horse", "STOCK", "HORSE"),
    THOROUGHBRED("Thoroughbred", "HOT-BLOODED", "HORSE"),
    TOKARA_PONY("Tokara Pony", "PONY", "PONY"),
    TORI_HORSE("Tori Horse", "WARMBLOOD", "COB"),
    TRAKHNER("Trakehner", "WARMBLOOD", "HORSE"),
    UKRAINIAN_SADDLE_HORSE("Ukrainian Saddle Horse", "WARMBLOOD", "HORSE"),
    VLAAMPERD("Vlaamperd", "BAROQUE", "HORSE"),
    VLADIMIR_HEAVY_DRAFT("Vladimir Heavy Draft", "DRAFT", "HORSE"),
    VYATKA_HORSE("Vyatka Horse", "PONY", "PONY"),
    WELARA_HORSE("Welara Horse", "PONY", "PONY"),
    WELSH_PONY("Welsh Pony", "PONY", "PONY"),
    WELSH_COB("Welsh Cob", "PONY", "COB"),
    WEST_AFRICAN_BARB("West African Barb", "HOT-BLOODED", "COB"),
    WESTERN_SUDAN_PONY("Western Sudan Pony", "PONY", "PONY"),
    WESTPHALIAN("Westphalian", "WARMBLOOD", "HORSE"),
    WIELKOPOLSKI_HORSE("Wielkopolski Horse", "WARMBLOOD", "HORSE"),
    XILINGOL_HORSE("Xilingol Horse", "WARMBLOOD", "COB"),
    YAKUT_HORSE("Yakut Horse", "EXOTIC", "PONY"),
    YANQI_HORSE("Yanqi Horse", "STOCK", "COB"),
    YILI_HORSE("Yili Horse", "STOCK", "COB"),
    YONAGUNI_HORSE("Yonaguni Horse", "PONY", "PONY"),
    ZANISKARI_PONY("Zaniskari Pony", "EXOTIC", "PONY"),
    ZHEMAICHU_HORSE("Zhemaichu Horse", "PONY", "PONY");

    private final String name;
    private final String type;
    private final String size;

    // Constructor
    Breed(String name, String type, String size, double minimumHands, double maximumHands) {
        this.name = name;
        this.type = type;
        this.size = size;
    }

    public String getName() {
        return name;
    }

    public String getType() {
        return type;
    }

    public String getSize() {
        return size;
    }

    @Override
    public String toString() {
        return name + " (" + type + ", " + size + ")";
    }
}
