package endcrypt.equinoxEquestrian.equine.enums;

public enum Breed {
    AEGIDIENBERGER("Aegidienberger"),
    AKHAL_TEKE("Akhal-Teke"),
    AMERICAN_INDIAN_HORSE("American Indian Horse"),
    AMERICAN_MINIATURE_HORSE("American Miniature Horse"),
    AMERICAN_PAINT_HORSE("American Paint Horse"),
    AMERICAN_QUARTER_HORSE("American Quarter Horse"),
    AMERICAN_SADDLEBRED("American Saddlebred"),
    AMERICAN_SHETLAND("American Shetland"),
    AMERICAN_SPORT_PONY("American Sport Pony"),
    AMERICAN_SUGARBUSH_HARLEQUIN_DRAFT("American Sugarbush Harlequin Draft"),
    AMERICAN_WARMBLOOD("American Warmblood"),
    ANDALUSIAN("Andalusian"),
    ANGLO_ARABIAN("Anglo-Arabian"),
    APPALOOSA("Appaloosa"),
    APPENDIX_HORSE("Appendix Horse"),
    ARABIAN("Arabian"),
    ARALOOSA("Araloosa"),
    ARDENNES("Ardennes"),
    AUSTRALIAN_BRUMBY("Australian Brumby"),
    AUSTRALIAN_RIDING_PONY("Australian Riding Pony"),
    AUSTRALIAN_STOCK_HORSE("Australian Stock Horse"),
    AUSTRALIAN_WARMBLOOD("Australian Warmblood"),
    AUSTRIAN_WARMBLOOD("Austrian Warmblood"),
    AZTECA("Azteca"),
    BARB_HORSE("Barb Horse"),
    BAROCK_PINTO("Barock Pinto"),
    BAVARIAN_WARMBLOOD("Bavarian Warmblood"),
    BAJAU_PONY("Bajau Pony"),
    BLAZER("Blazer"),
    BELGIAN_DRAFT("Belgian Draft"),
    BELGIAN_RIDING_PONY("Belgian Riding Pony"),
    BELGIAN_SPORT_HORSE("Belgian Sport Horse"),
    BELGIAN_WARMBLOOD("Belgian Warmblood"),
    BLACK_FOREST_HORSE("Black Forest Horse"),
    BOULONNAIS("Boulonnais"),
    BRAZILIAN_SPORT_HORSE("Brazilian Sport Horse"),
    BRETON("Breton"),
    BRITISH_RIDING_PONY("British Riding Pony"),
    BRITISH_SPOTTED_PONY("British Spotted Pony"),
    BUDYONNY("Budyonny"),
    CALABRESE("Calabrese"),
    CAMARGUE("Camargue"),
    CAMPOLINA("Campolina"),
    CANADIAN_SPORT_HORSE("Canadian Sport Horse"),
    CASPIAN_HORSE("Caspian Horse"),
    CHEVAL_CANADIAN("Cheval Canadian"),
    CHINCOTEAGUE_PONY("Chincoteague Pony"),
    CLEVELAND_BAY("Cleveland Bay"),
    CLYDESDALE("Clydesdale"),
    CONNEMARA("Connemara"),
    COLORADO_RANGER("Colorado Ranger"),
    CRIOLLO("Criollo"),
    CURLY_HORSE("Curly Horse"),
    CZECH_WARMBLOOD("Czech Warmblood"),
    DALES_PONY("Dales Pony"),
    DANISH_SPORT_PONY("Danish Sport Pony"),
    DANISH_WARMBLOOD("Danish Warmblood"),
    DARTMOOR_PONY("Dartmoor Pony"),
    DOLE_HORSE("Dole Horse"),
    DUTCH_HARNESS_HORSE("Dutch Harness Horse"),
    DUTCH_HEAVY_DRAFT("Dutch Heavy Draft"),
    DUTCH_RIDING_PONY("Dutch Riding Pony"),
    DUTCH_WARMBLOOD("Dutch Warmblood"),
    EXMOOR_PONY("Exmoor Pony"),
    ERISKAY_PONY("Eriskay Pony"),
    FALABELLA("Falabella"),
    FAROESE_PONY("Faroese Pony"),
    FELL_PONY("Fell Pony"),
    FINNISH_WARMBLOOD("Finnish Warmblood"),
    FLORIDA_CRACKER_HORSE("Florida Cracker Horse"),
    FREDERIKSBORGER("Frederiksborger"),
    FRENCH_SADDLE_PONY("French Saddle Pony"),
    FRENCH_TROTTER("French Trotter"),
    FRIESIAN("Friesian"),
    FRIESIAN_SPORT_HORSE("Friesian Sport Horse"),
    GALICENO("Galiceno"),
    GEORGIAN_GRANDE("Georgian Grande"),
    GERMAN_RIDING_PONY("German Riding Pony"),
    GERMAN_SPORT_HORSE("German Sport Horse"),
    GERMAN_WARMBLOOD("German Warmblood"),
    GRONINGEN_HORSE("Groningen Horse"),
    GYPSY_VANNER("Gypsy Vanner"),
    HACKNEY_HORSES("Hackney Horses"),
    HAFLINGER_HORSES("Haflinger Horses"),
    HANOVERIAN_HORSES("Hanoverian Horses"),
    HEQU_HORSES("Hequ Horses"),
    HIGHLAND_PONY("Highland Pony"),
    HOKKAIDO_HORSES("Hokkaido Horses"),
    HUCUL_HORSES("Hucul Horses"),
    HUNGARIAN_WARMBLOOD_HORSES("Hungarian Warmblood Horses"),
    ICELANDIC_HORSES("Icelandic Horses"),
    IOMUD_HORSES("Iomud Horses"),
    IRISH_DRAUGHT_HORSES("Irish Draught Horses"),
    JINZHOU_HORSES("Jinzhou Horses"),
    JUTLAND_HORSES("Jutland Horses"),
    KABARDA_HORSES("Kabarda Horses"),
    KARABAIR_HORSES("Karabair Horses"),
    KARABAKH_HORSES("Karabakh Horses"),
    KAZAKH_HORSES("Kazakh Horses"),
    KERRY_BOG_PONY("Kerry Bog Pony"),
    KIGER_MUSTANG_HORSES("Kiger Mustang Horses"),
    KIRDI_PONY("Kirdi Pony"),
    KISBER_FELVER_HORSES("Kisber Felver Horses"),
    KISO_HORSES("Kiso Horses"),
    KLADRUBY_HORSES("Kladruby Horses"),
    KNABSTRUP_HORSES("Knabstrup Horses"),
    KUSHUM_HORSES("Kushum Horses"),
    KUSTANAI_HORSES("Kustanai Horses"),
    LATVIAN_HORSES("Latvian Horses"),
    LITHUANIAN_HEAVY_DRAFT_HORSES("Lithuanian Heavy Draft Horses"),
    LIPIZZAN_HORSES("Lipizzan Horses"),
    LOKAI_HORSES("Lokai Horses"),
    LOSINO_HORSES("Losino Horses"),
    LUSITANO_HORSES("Lusitano Horses"),
    MALOPOLSKI_HORSES("Malopolski Horses"),
    MANGALARGA_HORSES("Mangalarga Horses"),
    MARWARI_HORSES("Marwari Horses"),
    MBAYAR_PONY("M'Bayar Pony"),
    MERENS_PONY("Mérens Pony"),
    MESSARA_HORSES("Messara Horses"),
    MINIATURE_HORSES("Miniature Horses"),
    MISAKI_HORSES("Misaki Horses"),
    MISSOURI_FOX_TROTTING_HORSES("Missouri Fox Trotting Horses"),
    MIYAKO_HORSES("Miyako Horses"),
    MONGOLIAN_HORSES("Mongolian Horses"),
    MORAB_HORSES("Morab Horses"),
    MORGAN_HORSES("Morgan Horses"),
    MOYLE_HORSES("Moyle Horses"),
    MUSTANG_HORSES("Mustang Horses"),
    MURGESE_HORSES("Murgese Horses"),
    NATIONAL_SHOW_HORSES("National Show Horses"),
    NEW_FOREST_PONY("New Forest Pony"),
    NEW_KIRGIZ_HORSES("New Kirgiz Horses"),
    NEWFOUNDLAND_PONY("Newfoundland Pony"),
    NOMA_HORSES("Noma Horses"),
    NOOITGEDACHT_PONY("Nooitgedacht Pony"),
    NORIC_HORSES("Noric Horses"),
    NORDLAND_HORSES("Nordland Horses"),
    NORTHEASTERN_CRIOULO_HORSES("Northeastern - Crioulo Horses"),
    NORTH_SWEDISH_HORSES("North Swedish Horses"),
    NORWEGIAN_FJORD_HORSES("Norwegian Fjord Horses"),
    OB_PONY("Ob Pony"),
    OLDENBURG_HORSES("Oldenburg Horses"),
    ORLOV_TROTTER_HORSES("Orlov Trotter Horses"),
    PAINT_HORSES("Paint Horses"),
    PALOMINO_HORSES("Palomino Horses"),
    PANTANEIRO_CRIOULO_HORSES("Pantaneiro - Crioulo Horses"),
    PASO_FINO_HORSES("Paso Fino Horses"),
    PERCHERON_HORSES("Percheron Horses"),
    PERUVIAN_PASO_HORSES("Peruvian Paso Horses"),
    PINDOS_PONY("Pindos Pony"),
    PINIA_HORSES("Pinia Horses"),
    PINTABIAN_HORSES("Pintabian Horses"),
    PINTO_HORSES("Pinto Horses"),
    PINTALOOSA_HORSES("Pintaloosa Horses"),
    PONY_OF_THE_AMERICAS("Pony of the Americas"),
    POZAHORA_HORSES("Pozahora Horses"),
    QUARTER_PONY("Quarter Pony"),
    QUARTER_HORSES("Quarter Horses"),
    QUITTORS("Quittors"),
    QUOBBA_HORSES("Quobba Horses"),
    RAPIDIO_HORSES("Rapidio Horses"),
    RENZIAN_HORSES("Renzian Horses"),
    ROCK_MUSTANG_HORSES("Rock Mustang Horses"),
    ROCKIES_HORSES("Rockies Horses"),
    ROMANOV_HORSES("Romanov Horses"),
    ROMBI_HORSES("Rombi Horses"),
    RUSSIAN_HORSES("Russian Horses"),
    RUSSIAN_TROTTERS("Russian Trotters"),
    SELVATICO_HORSES("Selvatico Horses"),
    SHAGYA_HORSES("Shagya Horses"),
    SHELTIE_PONY("Sheltie Pony"),
    SHETLAND_PONY("Shetland Pony"),
    SIBERIAN_HORSES("Siberian Horses"),
    SILVER_HORSES("Silver Horses"),
    SIMON_HORSES("Simon Horses"),
    SLEIGHS_HORSES("Sleighs Horses"),
    SOUTH_RUSSIAN_HORSES("South Russian Horses"),
    SPANISH_HORSES("Spanish Horses"),
    SPORTSMAN_HORSES("Sportsman Horses"),
    SPOTTED_MUSTANG_HORSES("Spotted Mustang Horses"),
    STANFORD_HORSES("Stanford Horses"),
    SUFFOLK_HORSES("Suffolk Horses"),
    SWAN_HORSES("Swan Horses"),
    SWEDISH_HORSES("Swedish Horses"),
    SWEDISH_TROTTER_HORSES("Swedish Trotter Horses"),
    TACKOZ_HORSES("Tackoz Horses"),
    TEHRAN_HORSES("Tehran Horses"),
    TENNESSEE_WALKING_HORSES("Tennessee Walking Horses"),
    THOROUGHBRED_HORSES("Thoroughbred Horses"),
    TIGER_HORSES("Tiger Horses"),
    TOBAGO_PONY("Tobago Pony"),
    TRABEN_HORSES("Traben Horses"),
    TRAKENER_HORSES("Trakener Horses"),
    TROTTER_HORSES("Trotter Horses"),
    TROTZIE_HORSES("Trotzie Horses"),
    UNISTAR_HORSES("Unistar Horses"),
    VENTURI_HORSES("Venturi Horses"),
    VINCIAN_HORSES("Vincian Horses"),
    VITEZ_HORSES("Vitez Horses"),
    WAKES_HORSES("Wakes Horses"),
    WALNUT_HORSES("Walnut Horses"),
    WARMBLOOD_HORSES("Warmblood Horses"),
    WESTPHALIAN_HORSES("Westphalian Horses"),
    WHISK_HORSES("Whisk Horses"),
    WILLIAMSBURG_HORSES("Williamsburg Horses"),
    WINCHESTER_HORSES("Winchester Horses"),
    WOODSBORO_HORSES("Woodsboro Horses"),
    YAKUT_PONY("Yakut Pony"),
    YAROSLAV_HORSES("Yaroslav Horses"),
    YELLOWSTONE_HORSES("Yellowstone Horses"),
    ZEBRAS_HORSES("Zebras Horses");

    private final String breedName;

    Breed(String breedName) {
        this.breedName = breedName;
    }

    public String getBreedName() {
        return breedName;
    }
}
